[package]
name = "EvoSwap"
version = "1.0.0"
authors = []

[addresses]
evo = "0x5e069deb50049cff0522330a50a858cc91ad3ef554cb39d3541d480dde7bc357"
dev = "0x2c5796ed26cb904a336bb51e1ad41dac38daf2e2f5e8226efeec22eb4e259d7e"

admin = "0x2c5796ed26cb904a336bb51e1ad41dac38daf2e2f5e8226efeec22eb4e259d7e"
treasury = "0x1c6b743bea39d60fd1277e10a5e0bc2e91ba46dbe64d5077fa263fc6f38bf272"

alice = "0x123"
bob = "0x456"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.CoinDeployer]
local = "./CoinDeployer"

[dev-dependencies]