[package]
name = "CoinDeployer"
version = "1.0.0"
authors = []

[addresses]
evo_framework = "0x2c5796ed26cb904a336bb51e1ad41dac38daf2e2f5e8226efeec22eb4e259d7e"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dev-dependencies]